version: "3"

volumes:
  postgres:

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=anvil
      - POSTGRES_DB=anvil
      - POSTGRES_PASSWORD=anvil
    pull_policy: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anvil"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: ghcr.io/anvilistas/amoni-app-server/app:latest
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "3030:3030"
    volumes:
      - ./app:/app
      - ./.anvil_data:/anvil_data
    working_dir: /app
    command: anvil-app-server --config-file config.yaml
    pull_policy: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
