version: "3"

volumes:
  postgresql:

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=anvil
      - POSTGRES_DB=anvil
      - POSTGRES_PASSWORD=anvil
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anvil"]
      interval: 2s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: docker/app_server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "3030:3030"
    volumes:
      - ./app:/app
      - ./logs:/anvil_data
    working_dir: /app
    command: anvil-app-server --config-file config.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  test_runner:
    image: ghcr.io/anvilistas/amoni/test_runner:latest
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./tests:/code/tests
    command: python -m pytest
  theme_builder:
    build:
      context: .
      dockerfile: docker/theme_builder/Dockerfile
    volumes:
      - ./app:/app
      - ./theme:/theme
