app: /app/{{ cookiecutter.app_folder_name }}
data-dir: /anvil_data
database: jdbc:postgresql://db/anvil?username=anvil&password=anvil
uplink-key: uplink-key
client-uplink-key: client-uplink-key
auto-migrate: true
